### PR TITLE
Added a default print operator

### PR DESCRIPTION
**Pull request by PydraxAlpta**
Added a simple default print operator so that you can print the result objects in console to see them

### CODE REVIEW

**Comment by ScrappyCocco** [comment]
Hello and thanks for the Pull Request @PydraxAlpta 

I am sorry but I can't accept this code in this current state
According to [docs.python](https://docs.python.org/3/reference/datamodel.html#object.__repr__) and [python-str-repr](https://www.journaldev.com/22460/python-str-repr-functions), the `__repr__` function should return a string that rapresent an object allowing to re-create it.

If you want a human-readable function you should use `__str__`, but as you can see from the links above, it should return the string, not print it.

Keep me updated ^^

**Comment by PydraxAlpta** [comment]
Ah okay, thank you, I am not very familiar with the python special functions. I'll change it to a full string, and result it. I must have misunderstood the usage of the __repr__ method. I was trying to make this so I can search from console instead of accidentally being spoiled on a google search, so I did do some hasty work there.

**Comment by ScrappyCocco** [comment]
I'd suggest that instead of doing that big list you could just have changed each line with a string concat using +=, is easier to read and to edit

I'm gonna close this PR, if you want to submit that code I'd suggest to do this:

- Delete your patch branch and restart the edit from scratch so we don't have many commits
- Create a simple string method, just
```python
string = "var1:" + str(var1)
string += "var2:" + str(var2)
```
Will do in my opinion

- When you have a good `__str__` add a test line in a test inside _test_normal_request.py_ and _test_async_request.py_ that actually call that method and check that the content is correct. Comparing the exact two same strings might be too difficult because the game time change over time, so consider using `startswith()` to check only the first part of the full string returned by `__str__`.

If you don't know how to execute tests to test the code you can google or ask me here, but is pretty easy, is basically:
```
pip install .
nosetests howlongtobeatpy
```

Most good IDEs such as PyCharm help you doing that

If you have any question keep using this PR, I'll be happy to help ^^ 
Take your time to learn Python and provide a good PR, no hurries

PS: If you prefer to let me do the edit instead, feel free to open an Issue and I'll add this code for you by myself

**Comment by PydraxAlpta** [comment]
Alright, I'll look into the things you mentioned in a few days. I'd prefer to do it myself as it is an experience for me to learn both tests and dealing with public repos. And yeah, I realized that me making a long tuple is not good code, definitely should have done it better.
Thank you for being patient with me 😄

**Pull request closed without merging**
