### PR TITLE
another fix for the url changing

### PR DESCRIPTION
**Pull request by rarDevelopment**
The URL has changed once again!

### CODE REVIEW

**Comment by xavdid** [comment]
I think this will work but it may be worth assuming the url will change again in the future (or swap every day or something) and accommodate that. I'd be surprised if this is the last change like this we see!

**Comment by rarDevelopment** [comment]
> I think this will work but it may be worth assuming the url will change again in the future (or swap every day or something) and accommodate that. I'd be surprised if this is the last change like this we see!

Agreed. Unfortunately, the nature of the changes sometimes varies beyond just the URL change, so there are a lot of ways it could still break in the future. Either way, accommodating the URL makes sense, I'll leave that to @ScrappyCocco here as I've got my own spots to make such accommodations 🥲

**Review by ScrappyCocco — APPROVED** [review]
Test passed, review ok

**Comment by ScrappyCocco** [comment]
@xavdid what's your idea, keep a list of possible url to try? You can open an issue to discuss that

**Pull request merged**
