### PR TITLE
fixes for api changes

### PR DESCRIPTION
**Pull request by rarDevelopment**
These are the latest changes I've found. I wasn't sure how to test locally however, so this hasn't been tested and I might have missed something!

### CODE REVIEW

**Comment by ScrappyCocco** [comment]
As you can see Github tested your branch and it works!
Thank you so much for the help

**Comment by Baggio94** [comment]
Hello 
how can we apply this fix to the plugin directly in the steam deck ?
thanks

**Comment by ScrappyCocco** [comment]
@Baggio94 what plugin are you talking about?

**Comment by Baggio94** [comment]
> @Baggio94 what plugin are you talking about?

HLTB

**Comment by ScrappyCocco** [comment]
@Baggio94 I don't personally develop or support a Steam Deck plugin, you should contact the maintainers, I think it could be https://github.com/hulkrelax/hltb-for-deck/tree/main

**Pull request merged**
